<a href="https://colab.research.google.com/github/ccloveak/Study_Notes/blob/master/Python_%E6%95%B0%E6%8D%AE%E5%88%86%E6%9E%90%E5%B8%88%E5%BF%85%E5%A4%87%E7%9A%84%E5%85%A5%E9%97%A8%E5%AD%A6%E4%B9%A0%E8%B7%AF%E7%BA%BF%E5%92%8C%E6%8A%80%E8%83%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#入门学习路线

###1.1 统计学基本知识
概率，平均值，中位数，众数，四分位数，期望，标准差，方差，协方差，相关系数


###1.2 算法
用算法实现回归，分类，聚类分析 

###1.3 编程语言及工具
python

***
***

#数据整理

数据整理，英文名称 data munging，是指在获取到的原数据基础上，理解这些业务数据，整理清洗它们，作为接下来算法建模的输入数据

###2.1 理解业务数据
认真理解业务数据，可以试着理解去每个特征，观察每个特征，理解它们对结果的影响程度

####可视化工具： seaborn 

In [0]:
#缺train数据集
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
colormap = plt.cm.RdBu
plt.figure(figsize=(14,12))
sns.heatmap(train.astype(float).corr(),linewidths=0.1,vmax=1.0, square=True, cmap=colormap, linecolor='white', annot=True)

###2.2 明确各个特征的类型
明确数据类型，对数据进行筛选  
one-hot 编码  
dummy variable 虚拟变量


###2.3 找出异常数据
数据存在异常值，绘制箱形图，看一看百分位数  
了解数据范围，设定最大值、最小值限度

###2.4 面对缺失值
1.填充缺失数据  
2.彻底删除此字段

###2.5 数据不均衡
数据量越大，不均衡的问题越容易解决
数据量很小，解决起来就比较困难
***
***


#Python 入门必备知识
Python 语言主要的特点，通俗的说就是语法简洁，开发效率高，基于 Python 的开发生态环境比较友好。

###3.1 Python 最常用的对象
Python 最常用的几个对象： list、dict、tuple 以及它们三者的灵活组合。  
list`[ ]` 可以看作是线性表和链表的结合体 
dict`{ }`可以看作是 key-value 对的组合 
tuple`( )`是不可更改的 "list"



####3.1.1 dict 核心知识
dict 就是一种字典结构，key 唯一  
两种方法创建dict  
1.直接 {}  
2.dict 构造函数创建

In [4]:
d = {'a':[1,2,3], 'b':['gz','lg','zx']}
d

{'a': [1, 2, 3], 'b': ['gz', 'lg', 'zx']}

In [5]:
d = dict.fromkeys(['a','b'],[1,2,5])
d

{'a': [1, 2, 5], 'b': [1, 2, 5]}

#####字典内元素的增加、删除、更新、访问
增加元素对于 dict 而言就是增加一个键值对

In [6]:
d = dict.fromkeys(['a','b'],[1,2,3])
d

{'a': [1, 2, 3], 'b': [1, 2, 3]}

In [7]:
d['c'] = ['gz','lg'] 
d

{'a': [1, 2, 3], 'b': [1, 2, 3], 'c': ['gz', 'lg']}

如果添加一个键值对时，原字典中此键已经存在，则直接更新

In [8]:
d={'a': [1, 2, 3], 'b': [1, 2, 3], 'c': ['gz', 'lg']}
d

{'a': [1, 2, 3], 'b': [1, 2, 3], 'c': ['gz', 'lg']}

In [9]:
d['b'] = [3,5,8]
d

{'a': [1, 2, 3], 'b': [3, 5, 8], 'c': ['gz', 'lg']}

想要删除字典中的某个键值对时，使用 pop，传入想要删除的键值对的键

In [10]:
d

{'a': [1, 2, 3], 'b': [3, 5, 8], 'c': ['gz', 'lg']}

In [11]:
d.pop('b')

[3, 5, 8]

In [12]:
d

{'a': [1, 2, 3], 'c': ['gz', 'lg']}

如果字典中不存在此键，则返回设置的默认值，比如我们自己设置的： 'key is not in dict' 

In [13]:
d

{'a': [1, 2, 3], 'c': ['gz', 'lg']}

In [14]:
d.pop('b','key is not in dict')

'key is not in dict'

访问键值对，只能通过键，访问对应的值

In [15]:
d['a']

[1, 2, 3]

dict 是可迭代的对象类型，可以通过 for 遍历每个键值对，如下直接访问每个键

In [16]:
for i in d: 
    print(i)

a
c


要想访问每个键值对，可以借助字典的 items() 访问，items 方法返回字典内每项的视图

In [17]:
for item in d.items(): 
    print(item)

('a', [1, 2, 3])
('c', ['gz', 'lg'])


####3.1.2 tuple 和 set 简介
tuple 对象是以 () 创建的，set 对象是以 {} 创建的

In [18]:
t = ('a',[1,4,6],{'b':[4,2,0]})
t

('a', [1, 4, 6], {'b': [4, 2, 0]})

In [19]:
s = {1,4,6}
s

{1, 4, 6}

tuple 是不可更改的对象(immutable)，一旦创建，里面的元素就不能再改动了。  
set 是无重复元素的集合体，是可更改的对象(mutable)。

###3.2 Python 入门必备知识点

####3.2.1 对象上的特殊函数


#####常用的 Python 解释器 CPython

In [0]:
class student: 
    def __init__(self,name):
        self.name = name 
    def __len__(self):
        return len(self.name)

In [25]:
xiaoming = student('xiaoming')
len(xiaoming)

8

####3.2.2 列表生成式

In [26]:
[abs(i) for i in [-4,3,1,-9,2]]  

[4, 3, 1, 9, 2]

结合 if 和 else，写起来更加简洁

In [29]:
[i+1 if i>0 else i+1 for i in [-4,3,1,-9,2]]

[-3, 4, 2, -8, 3]

In [30]:
[i+0 if i>0 else i+1 for i in [-4,3,1,-9,2]]

[-3, 3, 1, -8, 2]

In [31]:
[i+2 if i>0 else i+1 for i in [-4,3,1,-9,2]]

[-3, 5, 3, -8, 4]

In [32]:
[i+3 if i>0 else i+1 for i in [-4,3,1,-9,2]]

[-3, 6, 4, -8, 5]

####3.2.3 位置参数和关键字参数
位置参数 ( positional argument ) 和关键字参数( keyword argument ) 

In [0]:
def fun(*args, **kwargs): 
    print(args,kwargs)


`*args`表示位置参数，`**kwargs`表示关键字参数



In [34]:
fun([4,3,1],name = 'gz', color = 'red') 

([4, 3, 1],) {'name': 'gz', 'color': 'red'}


*位置参数不能位于关键字参数后面*
***
***

#NumPy 入门必备知识

###4.1 ndarray 对象

In [0]:
import numpy as np

In [37]:
n1d = np.array([1,4,5])
n1d

array([1, 4, 5])

In [38]:
[1,4,5]*3

[1, 4, 5, 1, 4, 5, 1, 4, 5]

In [39]:
n1d*3

array([ 3, 12, 15])

In [40]:
[i*3 for i in [1,4,5]]

[3, 12, 15]

###4.2 NumPy 的向量化增强
linspace 默认线性切分 50 份，且默认包含边界值

In [41]:
b = np.linspace(0,10)
b

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [42]:
b + 1

array([ 1.        ,  1.20408163,  1.40816327,  1.6122449 ,  1.81632653,
        2.02040816,  2.2244898 ,  2.42857143,  2.63265306,  2.83673469,
        3.04081633,  3.24489796,  3.44897959,  3.65306122,  3.85714286,
        4.06122449,  4.26530612,  4.46938776,  4.67346939,  4.87755102,
        5.08163265,  5.28571429,  5.48979592,  5.69387755,  5.89795918,
        6.10204082,  6.30612245,  6.51020408,  6.71428571,  6.91836735,
        7.12244898,  7.32653061,  7.53061224,  7.73469388,  7.93877551,
        8.14285714,  8.34693878,  8.55102041,  8.75510204,  8.95918367,
        9.16326531,  9.36734694,  9.57142857,  9.7755102 ,  9.97959184,
       10.18367347, 10.3877551 , 10.59183673, 10.79591837, 11.        ])

#####增强 myabs 函数功能，使之具备处理 list 的能力
NumPy 的向量化函数 vectorize

In [45]:
def myabs(a):
    return abs(a)
zq_myabs = np.vectorize(myabs)
zq_myabs([1,3,-5])

array([1, 3, 5])

###4.3 NumPy 的传播机制
1.如果两个数组的末尾维度（trailing dimension)的长度相符  
2.参与计算的某个维度长度为 1
广播会在缺失和（或）长度为 1 的维度上进行


In [46]:
a = np.array([[1],[-5],[3]]) 
b = np.array([[5,2,4,9]]) 
a + b

array([[ 6,  3,  5, 10],
       [ 0, -3, -1,  4],
       [ 8,  5,  7, 12]])

In [47]:
a.shape

(3, 1)

In [48]:
b.shape

(1, 4)

***
***

#Pandas 数据分析必备入门知识


###5.1 类一维数组 Series
Series 是 pandas 两大数据结构中（DataFrame，Series）的一种。  
Series 是一种类似于一维数组的对象，它由一组数据（各种 NumPy 数据类型）以及一组与之相关的数据标签和索引组成。  
Series 对象也是一个 NumPy 的数组，因此 NumPy 的数组处理函数可以直接对 Series 进行处理。  
Series 除了可以使用位置索引作为下标存取元素之外，还可以使用标签下标存取元素。

#####每个 Series 对象都由两个数组组成
1. index：它是从 NumPy 数组继承的 Index 对象，保存标签信息。  
2. values：保存值的 NumPy 数组。

####5.1.1 创建 Series


```
Series(data=None, index=None, dtype=None, name=None)
```
data 为数据部分，index 为标签部分，省略下默认为自增整数索引，dtype 为 str, numpy.dtype, or **ExtensionDtype**



创建一个 series

In [51]:
import pandas as pd
ps = pd.Series(data=[-3,2,1],index=['a','f','b'],dtype=np.float32)
ps

a   -3.0
f    2.0
b    1.0
dtype: float32

####5.1.2 增加元素
在 ps 基础上增加一个元素，使用 append

In [52]:
ps.append(pd.Series(data=[-8.0],index=['f']))

a   -3.0
f    2.0
b    1.0
f   -8.0
dtype: float64

Pandas 允许包含重复的标签

In [54]:
psn = ps.append(pd.Series(data=[-8.0],index=['f']))
psn

a   -3.0
f    2.0
b    1.0
f   -8.0
dtype: float64

In [55]:
psn['f']

f    2.0
f   -8.0
dtype: float64

利用标签访问元素，返回所有带标签的数据

####5.1.3 删除元素
使用 drop 删除指定标签的数据

In [56]:
ps

a   -3.0
f    2.0
b    1.0
dtype: float32

In [57]:
psd = ps.drop('f')
psd

a   -3.0
b    1.0
dtype: float32

*不管是 append 操作，还是 drop 操作，都是发生在原数据的副本上*

####5.1.3 修改元素
改数据，直接通过修改的标签，更新对应的数据

In [58]:
psn

a   -3.0
f    2.0
b    1.0
f   -8.0
dtype: float64

In [59]:
psn['f'] = 10.0
psn

a    -3.0
f    10.0
b     1.0
f    10.0
dtype: float64

####5.1.4 访问元素
Pandas 提供两种方法  
1.通过默认的整数索引，或者在 Series 对象未被显示的指定 label 时，都是通过索引访问  
2.通过标签访问

In [60]:
ps

a   -3.0
f    2.0
b    1.0
dtype: float32

In [61]:
ps[2]

1.0

In [62]:
ps['b']

1.0

###5.2 类二维数组 DataFrame
DataFrame 是 Pandas 的两个重要数据结构的另一个，可以看做是 Series 的容器。  


DataFrame 同时具有行、列标签，是二维的数组，行方向轴 axis 为 0, 列方向 axis 为 1


```
axis : {0 or 'index', 1 or 'columns'}
```



####5.2.1 创建 DataFrame


```
DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)
```



In [63]:
df = pd.DataFrame([['gz',4.0,'2019-01-01'],['lg',1.2,'2019-06-01']],index = ['a','f'], columns = ['nm', 'y','da'])                          
df

nm    y          da
a  gz  4.0  2019-01-01
f  lg  1.2  2019-06-01

可以通过字典传入，得到一样的数据框

In [64]:
df2 = pd.DataFrame({'nm':['gz','lg'],'y':[4.0,1.2], 'da':['2019-01-01', '2019-06-01']},index = ['a','f']) 
df2

nm    y          da
a  gz  4.0  2019-01-01
f  lg  1.2  2019-06-01

####5.2.2 增加数据

In [91]:
dfn = df.append(pd.Series(data=['zx',3.6,'2019-05-01'],index=['nm','y','da'],name='b'))
dfn

nm    y          da
a  gz  4.0  2019-01-01
f  lg  1.2  2019-06-01
b  zx  3.6  2019-05-01

Series 的 index 与数据框的 column 对齐，name 与数据框的 index 对齐

####5.2.3 删除数据


In [92]:
dfn.drop('b')

nm    y          da
a  gz  4.0  2019-01-01
f  lg  1.2  2019-06-01

如果要删除某列，需要设定 axis 为 1,

In [93]:
In [147]: dfn.drop('y',axis=1)

nm          da
a  gz  2019-01-01
f  lg  2019-06-01
b  zx  2019-05-01

####5.2.4 修改数据
修改依然是先通过索引或标签定位到数据，然后修改

In [94]:
dfn.loc['a','da']='2019-04-01'
dfn 

nm    y          da
a  gz  4.0  2019-04-01
f  lg  1.2  2019-06-01
b  zx  3.6  2019-05-01

***链式赋值( chained assignment)***

####5.2.5 访问数据
Pandas 推荐使用访问接口 iloc、loc访问数据

In [95]:
df

nm    y          da
a  gz  4.0  2019-01-01
f  lg  1.2  2019-06-01

In [96]:
df.iloc[1,:] 

nm            lg
y            1.2
da    2019-06-01
Name: f, dtype: object

In [97]:
df.loc['f',:]

nm            lg
y            1.2
da    2019-06-01
Name: f, dtype: object

In [98]:
df.loc['f','nm']

'lg'

###5.3 必备的 20 个统计学函数

|函数|英文术语|中文|
| ------ | ------ | ------ |
count	| Number of non-null observations| 观测值的个数  
sum	| Sum of values	| 求和
mean	| Mean of values	| 求平均值
mad	| Mean absolute deviation| 	平均绝对方差
median	| Arithmetic median of values	| 中位数
min| 	Minimum| 	最小值
max	| Maximum	| 最大值
mode	| Mode	| 众数
abs	| Absolute Value| 	绝对值
prod	| Product of values	| 乘积
std	| Bessel-corrected sample standard deviation	| 标准差
var| 	Unbiased variance	| 方差
sem	| Standard error of the mean	| 标准误差
skew	| Sample skewness (3rd moment)	| 偏度系数
kurt| 	Sample kurtosis (4th moment)| 	峰度
quantile	| Sample quantile (value at %)	| 分位数
cumsum	| Cumulative sum	| 累加
cumprod	| Cumulative product	| 累乘
cummax| 	Cumulative maximum| 	累最大值
cummin	| Cumulative minimum	| 累最小值
cov()	| covariance	| 协方差
corr()	| correlation	| 相关系数
rank()	| rank by values| 	排名
pct_change()	| time change| 	时间序列变化

###5.4 必备的缺失值处理技巧
Pandas 提供了一些便利的函数，可以帮助我们快速按照设想处理、解决空值

Pandas 提供了一些便利的函数，可以帮助我们快速按照设想处理、解决空值  
函数 isnull、notnull，可以帮助我们快速定位数据集中每个元素是否为空值

In [99]:
dfn

nm    y          da
a  gz  4.0  2019-04-01
f  lg  1.2  2019-06-01
b  zx  3.6  2019-05-01

In [100]:
pd.isnull(dfn1) 

nm      y     da
a  False  False  False
f  False  False  False
b  False  False  False

假设存在空值，可以使用 Pandas 中的 fillna 函数填充空值  
fillna 有一个关键参数： method，当设置 method 为 pad 时， 从上一个有效数据传播到下一个有效数据行。

使用默认值 1.0 填充 y 列:

In [101]:
dfn['y'] = dfn['y'].fillna(1.0)
dfn

nm    y          da
a  gz  4.0  2019-04-01
f  lg  1.2  2019-06-01
b  zx  3.6  2019-05-01

检测到了空值数据，但是不想做任何填充，而是仅仅想丢弃这些空值数据  
axis, how, 例如组合：axis = 0，how = any，表示某行只要某个元素为空值，就丢弃

In [103]:
dfn

nm    y          da
a  gz  4.0  2019-04-01
f  lg  1.2  2019-06-01
b  zx  3.6  2019-05-01

In [102]:
dfn.dropna(axis=0,how='any')

nm    y          da
a  gz  4.0  2019-04-01
f  lg  1.2  2019-06-01
b  zx  3.6  2019-05-01

###5.5 必备的数据透视处理函数
有类似 Excel 中提供的数据透视功能

构造数据：

In [107]:
df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo", "bar", "bar", "bar", "bar"],
                   "B": ["one", "one", "one", "two", "two", "one", "one", "two", "two"], 
                   "C": ["small", "large", "large", "small", "small", "large", "small", "small", "large"], 
                   "D": [1, 2, 2, 3, 3, 4, 5, 6, 7], 
                   "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})  
df                  

A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

In [108]:
pd.pivot_table(df, values=['D','E'], index=['A','B'], columns='C',aggfunc=[np.mean,np.max])               

mean                    amax                  
            D           E           D           E      
C       large small large small large small large small
A   B                                                  
bar one   4.0   5.0   6.0   8.0   4.0   5.0   6.0   8.0
    two   7.0   6.0   9.0   9.0   7.0   6.0   9.0   9.0
foo one   2.0   1.0   4.5   2.0   2.0   1.0   5.0   2.0
    two   NaN   3.0   NaN   5.5   NaN   3.0   NaN   6.0

#####分步解析数据透视的过程
以 A 和 B 两列为 index，一旦选定，内部实现中会根据 A 和 B 形成一个多级索引，并对数据分组。  
第二维度，也就是 axis 为 1 的维度，设置为 C 列，这样数据会被重构为这种二维表，并且如果聚合函数缺省情况下，默认统计平均值。  
*看不懂，胸口闷，脑壳疼*

In [109]:
pd.pivot_table(df, index=['A','B'],columns='C')

D           E      
C       large small large small
A   B                          
bar one   4.0   5.0   6.0   8.0
    two   7.0   6.0   9.0   9.0
foo one   2.0   1.0   4.5   2.0
    two   NaN   3.0   NaN   5.5

当为 pivot_table 设置上 values 来自哪些列，同时定义聚合函数后，就最终得到数据的透视结果。